// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actors.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createActor = `-- name: CreateActor :one
INSERT INTO actors (type, external_id, name, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, type, external_id, name, metadata, registered_at
`

type CreateActorParams struct {
	Type       ActorType `json:"type"`
	ExternalID *string   `json:"external_id"`
	Name       *string   `json:"name"`
	Metadata   []byte    `json:"metadata"`
}

func (q *Queries) CreateActor(ctx context.Context, arg CreateActorParams) (Actor, error) {
	row := q.db.QueryRow(ctx, createActor,
		arg.Type,
		arg.ExternalID,
		arg.Name,
		arg.Metadata,
	)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ExternalID,
		&i.Name,
		&i.Metadata,
		&i.RegisteredAt,
	)
	return i, err
}

const getActor = `-- name: GetActor :one
SELECT id, type, external_id, name, metadata, registered_at FROM actors WHERE id = $1
`

func (q *Queries) GetActor(ctx context.Context, id uuid.UUID) (Actor, error) {
	row := q.db.QueryRow(ctx, getActor, id)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ExternalID,
		&i.Name,
		&i.Metadata,
		&i.RegisteredAt,
	)
	return i, err
}

const getActorByExternalID = `-- name: GetActorByExternalID :one
SELECT id, type, external_id, name, metadata, registered_at FROM actors WHERE type = $1 AND external_id = $2
`

type GetActorByExternalIDParams struct {
	Type       ActorType `json:"type"`
	ExternalID *string   `json:"external_id"`
}

func (q *Queries) GetActorByExternalID(ctx context.Context, arg GetActorByExternalIDParams) (Actor, error) {
	row := q.db.QueryRow(ctx, getActorByExternalID, arg.Type, arg.ExternalID)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ExternalID,
		&i.Name,
		&i.Metadata,
		&i.RegisteredAt,
	)
	return i, err
}

const listActors = `-- name: ListActors :many
SELECT id, type, external_id, name, metadata, registered_at FROM actors ORDER BY registered_at DESC
`

func (q *Queries) ListActors(ctx context.Context) ([]Actor, error) {
	rows, err := q.db.Query(ctx, listActors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Actor{}
	for rows.Next() {
		var i Actor
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ExternalID,
			&i.Name,
			&i.Metadata,
			&i.RegisteredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActorsByType = `-- name: ListActorsByType :many
SELECT id, type, external_id, name, metadata, registered_at FROM actors WHERE type = $1 ORDER BY registered_at DESC
`

func (q *Queries) ListActorsByType(ctx context.Context, type_ ActorType) ([]Actor, error) {
	rows, err := q.db.Query(ctx, listActorsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Actor{}
	for rows.Next() {
		var i Actor
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ExternalID,
			&i.Name,
			&i.Metadata,
			&i.RegisteredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
