// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifacts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (scope_id, content_hash, content_type, uri, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, scope_id, content_hash, content_type, uri, metadata, created_at
`

type CreateArtifactParams struct {
	ScopeID     uuid.UUID `json:"scope_id"`
	ContentHash string    `json:"content_hash"`
	ContentType string    `json:"content_type"`
	Uri         *string   `json:"uri"`
	Metadata    []byte    `json:"metadata"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.ScopeID,
		arg.ContentHash,
		arg.ContentType,
		arg.Uri,
		arg.Metadata,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.ContentHash,
		&i.ContentType,
		&i.Uri,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, scope_id, content_hash, content_type, uri, metadata, created_at FROM artifacts WHERE id = $1
`

func (q *Queries) GetArtifact(ctx context.Context, id uuid.UUID) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.ContentHash,
		&i.ContentType,
		&i.Uri,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactByHash = `-- name: GetArtifactByHash :one
SELECT id, scope_id, content_hash, content_type, uri, metadata, created_at FROM artifacts WHERE scope_id = $1 AND content_hash = $2
`

type GetArtifactByHashParams struct {
	ScopeID     uuid.UUID `json:"scope_id"`
	ContentHash string    `json:"content_hash"`
}

func (q *Queries) GetArtifactByHash(ctx context.Context, arg GetArtifactByHashParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifactByHash, arg.ScopeID, arg.ContentHash)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.ContentHash,
		&i.ContentType,
		&i.Uri,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listArtifactsInScope = `-- name: ListArtifactsInScope :many
SELECT id, scope_id, content_hash, content_type, uri, metadata, created_at FROM artifacts WHERE scope_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListArtifactsInScopeParams struct {
	ScopeID uuid.UUID `json:"scope_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListArtifactsInScope(ctx context.Context, arg ListArtifactsInScopeParams) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsInScope, arg.ScopeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.ContentHash,
			&i.ContentType,
			&i.Uri,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
