// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEventsInScope = `-- name: CountEventsInScope :one
SELECT COUNT(*) FROM events WHERE scope_id = $1
`

func (q *Queries) CountEventsInScope(ctx context.Context, scopeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsInScope, scopeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCorrectionsForEvent = `-- name: GetCorrectionsForEvent :many
SELECT id, scope_id, actor_id, event_type_id, scope_sequence, intent, reason, correction_type, corrects_event_id, observed_at, decided_at, ingested_at, prev_event_hash, event_hash, payload FROM events
WHERE corrects_event_id = $1
ORDER BY scope_sequence ASC
`

func (q *Queries) GetCorrectionsForEvent(ctx context.Context, correctsEventID pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, getCorrectionsForEvent, correctsEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.ActorID,
			&i.EventTypeID,
			&i.ScopeSequence,
			&i.Intent,
			&i.Reason,
			&i.CorrectionType,
			&i.CorrectsEventID,
			&i.ObservedAt,
			&i.DecidedAt,
			&i.IngestedAt,
			&i.PrevEventHash,
			&i.EventHash,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvent = `-- name: GetEvent :one
SELECT id, scope_id, actor_id, event_type_id, scope_sequence, intent, reason, correction_type, corrects_event_id, observed_at, decided_at, ingested_at, prev_event_hash, event_hash, payload FROM events WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.ActorID,
		&i.EventTypeID,
		&i.ScopeSequence,
		&i.Intent,
		&i.Reason,
		&i.CorrectionType,
		&i.CorrectsEventID,
		&i.ObservedAt,
		&i.DecidedAt,
		&i.IngestedAt,
		&i.PrevEventHash,
		&i.EventHash,
		&i.Payload,
	)
	return i, err
}

const getEventByHash = `-- name: GetEventByHash :one
SELECT id, scope_id, actor_id, event_type_id, scope_sequence, intent, reason, correction_type, corrects_event_id, observed_at, decided_at, ingested_at, prev_event_hash, event_hash, payload FROM events WHERE event_hash = $1
`

func (q *Queries) GetEventByHash(ctx context.Context, eventHash string) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByHash, eventHash)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.ActorID,
		&i.EventTypeID,
		&i.ScopeSequence,
		&i.Intent,
		&i.Reason,
		&i.CorrectionType,
		&i.CorrectsEventID,
		&i.ObservedAt,
		&i.DecidedAt,
		&i.IngestedAt,
		&i.PrevEventHash,
		&i.EventHash,
		&i.Payload,
	)
	return i, err
}

const getEventsByActor = `-- name: GetEventsByActor :many
SELECT id, scope_id, actor_id, event_type_id, scope_sequence, intent, reason, correction_type, corrects_event_id, observed_at, decided_at, ingested_at, prev_event_hash, event_hash, payload FROM events
WHERE actor_id = $1
ORDER BY ingested_at DESC
LIMIT $2 OFFSET $3
`

type GetEventsByActorParams struct {
	ActorID uuid.UUID `json:"actor_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) GetEventsByActor(ctx context.Context, arg GetEventsByActorParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByActor, arg.ActorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.ActorID,
			&i.EventTypeID,
			&i.ScopeSequence,
			&i.Intent,
			&i.Reason,
			&i.CorrectionType,
			&i.CorrectsEventID,
			&i.ObservedAt,
			&i.DecidedAt,
			&i.IngestedAt,
			&i.PrevEventHash,
			&i.EventHash,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByScope = `-- name: GetEventsByScope :many
SELECT id, scope_id, actor_id, event_type_id, scope_sequence, intent, reason, correction_type, corrects_event_id, observed_at, decided_at, ingested_at, prev_event_hash, event_hash, payload FROM events
WHERE scope_id = $1
ORDER BY scope_sequence ASC
LIMIT $2 OFFSET $3
`

type GetEventsByScopeParams struct {
	ScopeID uuid.UUID `json:"scope_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) GetEventsByScope(ctx context.Context, arg GetEventsByScopeParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByScope, arg.ScopeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.ActorID,
			&i.EventTypeID,
			&i.ScopeSequence,
			&i.Intent,
			&i.Reason,
			&i.CorrectionType,
			&i.CorrectsEventID,
			&i.ObservedAt,
			&i.DecidedAt,
			&i.IngestedAt,
			&i.PrevEventHash,
			&i.EventHash,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastEventInScope = `-- name: GetLastEventInScope :one
SELECT id, scope_id, actor_id, event_type_id, scope_sequence, intent, reason, correction_type, corrects_event_id, observed_at, decided_at, ingested_at, prev_event_hash, event_hash, payload FROM events
WHERE scope_id = $1
ORDER BY scope_sequence DESC
LIMIT 1
`

func (q *Queries) GetLastEventInScope(ctx context.Context, scopeID uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getLastEventInScope, scopeID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.ActorID,
		&i.EventTypeID,
		&i.ScopeSequence,
		&i.Intent,
		&i.Reason,
		&i.CorrectionType,
		&i.CorrectsEventID,
		&i.ObservedAt,
		&i.DecidedAt,
		&i.IngestedAt,
		&i.PrevEventHash,
		&i.EventHash,
		&i.Payload,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (
    scope_id, actor_id, event_type_id, scope_sequence, intent, reason,
    correction_type, corrects_event_id, observed_at, decided_at,
    prev_event_hash, event_hash, payload
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, scope_id, actor_id, event_type_id, scope_sequence, intent, reason, correction_type, corrects_event_id, observed_at, decided_at, ingested_at, prev_event_hash, event_hash, payload
`

type InsertEventParams struct {
	ScopeID         uuid.UUID          `json:"scope_id"`
	ActorID         uuid.UUID          `json:"actor_id"`
	EventTypeID     uuid.UUID          `json:"event_type_id"`
	ScopeSequence   int64              `json:"scope_sequence"`
	Intent          EventIntent        `json:"intent"`
	Reason          *string            `json:"reason"`
	CorrectionType  NullCorrectionType `json:"correction_type"`
	CorrectsEventID pgtype.UUID        `json:"corrects_event_id"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
	DecidedAt       pgtype.Timestamptz `json:"decided_at"`
	PrevEventHash   *string            `json:"prev_event_hash"`
	EventHash       string             `json:"event_hash"`
	Payload         json.RawMessage    `json:"payload"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.ScopeID,
		arg.ActorID,
		arg.EventTypeID,
		arg.ScopeSequence,
		arg.Intent,
		arg.Reason,
		arg.CorrectionType,
		arg.CorrectsEventID,
		arg.ObservedAt,
		arg.DecidedAt,
		arg.PrevEventHash,
		arg.EventHash,
		arg.Payload,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.ActorID,
		&i.EventTypeID,
		&i.ScopeSequence,
		&i.Intent,
		&i.Reason,
		&i.CorrectionType,
		&i.CorrectsEventID,
		&i.ObservedAt,
		&i.DecidedAt,
		&i.IngestedAt,
		&i.PrevEventHash,
		&i.EventHash,
		&i.Payload,
	)
	return i, err
}
