// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_scores.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestScoreByType = `-- name: GetLatestScoreByType :one
SELECT id, event_id, type, value, category, scored_by, reason, metadata, created_at FROM event_scores
WHERE event_id = $1 AND type = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestScoreByTypeParams struct {
	EventID uuid.UUID `json:"event_id"`
	Type    ScoreType `json:"type"`
}

func (q *Queries) GetLatestScoreByType(ctx context.Context, arg GetLatestScoreByTypeParams) (EventScore, error) {
	row := q.db.QueryRow(ctx, getLatestScoreByType, arg.EventID, arg.Type)
	var i EventScore
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Type,
		&i.Value,
		&i.Category,
		&i.ScoredBy,
		&i.Reason,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getScoresByType = `-- name: GetScoresByType :many
SELECT id, event_id, type, value, category, scored_by, reason, metadata, created_at FROM event_scores WHERE event_id = $1 AND type = $2 ORDER BY created_at DESC
`

type GetScoresByTypeParams struct {
	EventID uuid.UUID `json:"event_id"`
	Type    ScoreType `json:"type"`
}

func (q *Queries) GetScoresByType(ctx context.Context, arg GetScoresByTypeParams) ([]EventScore, error) {
	rows, err := q.db.Query(ctx, getScoresByType, arg.EventID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventScore{}
	for rows.Next() {
		var i EventScore
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Type,
			&i.Value,
			&i.Category,
			&i.ScoredBy,
			&i.Reason,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScoresForEvent = `-- name: GetScoresForEvent :many
SELECT id, event_id, type, value, category, scored_by, reason, metadata, created_at FROM event_scores WHERE event_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetScoresForEvent(ctx context.Context, eventID uuid.UUID) ([]EventScore, error) {
	rows, err := q.db.Query(ctx, getScoresForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventScore{}
	for rows.Next() {
		var i EventScore
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Type,
			&i.Value,
			&i.Category,
			&i.ScoredBy,
			&i.Reason,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertScore = `-- name: InsertScore :one
INSERT INTO event_scores (event_id, type, value, category, scored_by, reason, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, event_id, type, value, category, scored_by, reason, metadata, created_at
`

type InsertScoreParams struct {
	EventID  uuid.UUID      `json:"event_id"`
	Type     ScoreType      `json:"type"`
	Value    pgtype.Numeric `json:"value"`
	Category ScoreCategory  `json:"category"`
	ScoredBy pgtype.UUID    `json:"scored_by"`
	Reason   *string        `json:"reason"`
	Metadata []byte         `json:"metadata"`
}

func (q *Queries) InsertScore(ctx context.Context, arg InsertScoreParams) (EventScore, error) {
	row := q.db.QueryRow(ctx, insertScore,
		arg.EventID,
		arg.Type,
		arg.Value,
		arg.Category,
		arg.ScoredBy,
		arg.Reason,
		arg.Metadata,
	)
	var i EventScore
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Type,
		&i.Value,
		&i.Category,
		&i.ScoredBy,
		&i.Reason,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
