// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_lineage.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createLineage = `-- name: CreateLineage :one
INSERT INTO event_lineage (parent_event_id, child_event_id, relationship)
VALUES ($1, $2, $3)
RETURNING id, parent_event_id, child_event_id, relationship
`

type CreateLineageParams struct {
	ParentEventID uuid.UUID `json:"parent_event_id"`
	ChildEventID  uuid.UUID `json:"child_event_id"`
	Relationship  string    `json:"relationship"`
}

func (q *Queries) CreateLineage(ctx context.Context, arg CreateLineageParams) (EventLineage, error) {
	row := q.db.QueryRow(ctx, createLineage, arg.ParentEventID, arg.ChildEventID, arg.Relationship)
	var i EventLineage
	err := row.Scan(
		&i.ID,
		&i.ParentEventID,
		&i.ChildEventID,
		&i.Relationship,
	)
	return i, err
}

const getChildren = `-- name: GetChildren :many
SELECT e.id, e.scope_id, e.actor_id, e.event_type_id, e.scope_sequence, e.intent, e.reason, e.correction_type, e.corrects_event_id, e.observed_at, e.decided_at, e.ingested_at, e.prev_event_hash, e.event_hash, e.payload FROM events e
JOIN event_lineage el ON el.child_event_id = e.id
WHERE el.parent_event_id = $1
`

func (q *Queries) GetChildren(ctx context.Context, parentEventID uuid.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, getChildren, parentEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.ActorID,
			&i.EventTypeID,
			&i.ScopeSequence,
			&i.Intent,
			&i.Reason,
			&i.CorrectionType,
			&i.CorrectsEventID,
			&i.ObservedAt,
			&i.DecidedAt,
			&i.IngestedAt,
			&i.PrevEventHash,
			&i.EventHash,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDirectChildIDs = `-- name: GetDirectChildIDs :many
SELECT child_event_id FROM event_lineage WHERE parent_event_id = $1
`

func (q *Queries) GetDirectChildIDs(ctx context.Context, parentEventID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getDirectChildIDs, parentEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var child_event_id uuid.UUID
		if err := rows.Scan(&child_event_id); err != nil {
			return nil, err
		}
		items = append(items, child_event_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDirectParentIDs = `-- name: GetDirectParentIDs :many
SELECT parent_event_id FROM event_lineage WHERE child_event_id = $1
`

func (q *Queries) GetDirectParentIDs(ctx context.Context, childEventID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getDirectParentIDs, childEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var parent_event_id uuid.UUID
		if err := rows.Scan(&parent_event_id); err != nil {
			return nil, err
		}
		items = append(items, parent_event_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLineageEdge = `-- name: GetLineageEdge :one
SELECT id, parent_event_id, child_event_id, relationship FROM event_lineage
WHERE parent_event_id = $1 AND child_event_id = $2
`

type GetLineageEdgeParams struct {
	ParentEventID uuid.UUID `json:"parent_event_id"`
	ChildEventID  uuid.UUID `json:"child_event_id"`
}

func (q *Queries) GetLineageEdge(ctx context.Context, arg GetLineageEdgeParams) (EventLineage, error) {
	row := q.db.QueryRow(ctx, getLineageEdge, arg.ParentEventID, arg.ChildEventID)
	var i EventLineage
	err := row.Scan(
		&i.ID,
		&i.ParentEventID,
		&i.ChildEventID,
		&i.Relationship,
	)
	return i, err
}

const getParents = `-- name: GetParents :many
SELECT e.id, e.scope_id, e.actor_id, e.event_type_id, e.scope_sequence, e.intent, e.reason, e.correction_type, e.corrects_event_id, e.observed_at, e.decided_at, e.ingested_at, e.prev_event_hash, e.event_hash, e.payload FROM events e
JOIN event_lineage el ON el.parent_event_id = e.id
WHERE el.child_event_id = $1
`

func (q *Queries) GetParents(ctx context.Context, childEventID uuid.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, getParents, childEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.ActorID,
			&i.EventTypeID,
			&i.ScopeSequence,
			&i.Intent,
			&i.Reason,
			&i.CorrectionType,
			&i.CorrectsEventID,
			&i.ObservedAt,
			&i.DecidedAt,
			&i.IngestedAt,
			&i.PrevEventHash,
			&i.EventHash,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
