// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ActorType string

const (
	ActorTypeHuman   ActorType = "human"
	ActorTypeLlm     ActorType = "llm"
	ActorTypeAgent   ActorType = "agent"
	ActorTypeService ActorType = "service"
	ActorTypeTool    ActorType = "tool"
)

func (e *ActorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActorType(s)
	case string:
		*e = ActorType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActorType: %T", src)
	}
	return nil
}

type NullActorType struct {
	ActorType ActorType `json:"actor_type"`
	Valid     bool      `json:"valid"` // Valid is true if ActorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActorType) Scan(value interface{}) error {
	if value == nil {
		ns.ActorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActorType), nil
}

type ArtifactRole string

const (
	ArtifactRoleInput  ArtifactRole = "input"
	ArtifactRoleOutput ArtifactRole = "output"
)

func (e *ArtifactRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArtifactRole(s)
	case string:
		*e = ArtifactRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ArtifactRole: %T", src)
	}
	return nil
}

type NullArtifactRole struct {
	ArtifactRole ArtifactRole `json:"artifact_role"`
	Valid        bool         `json:"valid"` // Valid is true if ArtifactRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArtifactRole) Scan(value interface{}) error {
	if value == nil {
		ns.ArtifactRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArtifactRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArtifactRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ArtifactRole), nil
}

type CorrectionType string

const (
	CorrectionTypeSupersede CorrectionType = "supersede"
	CorrectionTypeAmend     CorrectionType = "amend"
	CorrectionTypeRetract   CorrectionType = "retract"
)

func (e *CorrectionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CorrectionType(s)
	case string:
		*e = CorrectionType(s)
	default:
		return fmt.Errorf("unsupported scan type for CorrectionType: %T", src)
	}
	return nil
}

type NullCorrectionType struct {
	CorrectionType CorrectionType `json:"correction_type"`
	Valid          bool           `json:"valid"` // Valid is true if CorrectionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCorrectionType) Scan(value interface{}) error {
	if value == nil {
		ns.CorrectionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CorrectionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCorrectionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CorrectionType), nil
}

type EventIntent string

const (
	EventIntentExploration EventIntent = "exploration"
	EventIntentSuggestion  EventIntent = "suggestion"
	EventIntentAssertion   EventIntent = "assertion"
	EventIntentDecision    EventIntent = "decision"
	EventIntentExecution   EventIntent = "execution"
)

func (e *EventIntent) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventIntent(s)
	case string:
		*e = EventIntent(s)
	default:
		return fmt.Errorf("unsupported scan type for EventIntent: %T", src)
	}
	return nil
}

type NullEventIntent struct {
	EventIntent EventIntent `json:"event_intent"`
	Valid       bool        `json:"valid"` // Valid is true if EventIntent is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventIntent) Scan(value interface{}) error {
	if value == nil {
		ns.EventIntent, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventIntent.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventIntent) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventIntent), nil
}

type ScoreCategory string

const (
	ScoreCategoryVeryLow  ScoreCategory = "very_low"
	ScoreCategoryLow      ScoreCategory = "low"
	ScoreCategoryModerate ScoreCategory = "moderate"
	ScoreCategoryHigh     ScoreCategory = "high"
	ScoreCategoryVeryHigh ScoreCategory = "very_high"
)

func (e *ScoreCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScoreCategory(s)
	case string:
		*e = ScoreCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for ScoreCategory: %T", src)
	}
	return nil
}

type NullScoreCategory struct {
	ScoreCategory ScoreCategory `json:"score_category"`
	Valid         bool          `json:"valid"` // Valid is true if ScoreCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScoreCategory) Scan(value interface{}) error {
	if value == nil {
		ns.ScoreCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScoreCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScoreCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScoreCategory), nil
}

type ScoreType string

const (
	ScoreTypeConfidence  ScoreType = "confidence"
	ScoreTypeRelevance   ScoreType = "relevance"
	ScoreTypeReliability ScoreType = "reliability"
	ScoreTypeAgreement   ScoreType = "agreement"
)

func (e *ScoreType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScoreType(s)
	case string:
		*e = ScoreType(s)
	default:
		return fmt.Errorf("unsupported scan type for ScoreType: %T", src)
	}
	return nil
}

type NullScoreType struct {
	ScoreType ScoreType `json:"score_type"`
	Valid     bool      `json:"valid"` // Valid is true if ScoreType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScoreType) Scan(value interface{}) error {
	if value == nil {
		ns.ScoreType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScoreType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScoreType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScoreType), nil
}

type Actor struct {
	ID           uuid.UUID `json:"id"`
	Type         ActorType `json:"type"`
	ExternalID   *string   `json:"external_id"`
	Name         *string   `json:"name"`
	Metadata     []byte    `json:"metadata"`
	RegisteredAt time.Time `json:"registered_at"`
}

type Artifact struct {
	ID          uuid.UUID `json:"id"`
	ScopeID     uuid.UUID `json:"scope_id"`
	ContentHash string    `json:"content_hash"`
	ContentType string    `json:"content_type"`
	Uri         *string   `json:"uri"`
	Metadata    []byte    `json:"metadata"`
	CreatedAt   time.Time `json:"created_at"`
}

// IMMUTABLE. Never updated or deleted. See append-only enforcement.
type Event struct {
	ID              uuid.UUID          `json:"id"`
	ScopeID         uuid.UUID          `json:"scope_id"`
	ActorID         uuid.UUID          `json:"actor_id"`
	EventTypeID     uuid.UUID          `json:"event_type_id"`
	ScopeSequence   int64              `json:"scope_sequence"`
	Intent          EventIntent        `json:"intent"`
	Reason          *string            `json:"reason"`
	CorrectionType  NullCorrectionType `json:"correction_type"`
	CorrectsEventID pgtype.UUID        `json:"corrects_event_id"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
	DecidedAt       pgtype.Timestamptz `json:"decided_at"`
	IngestedAt      time.Time          `json:"ingested_at"`
	PrevEventHash   *string            `json:"prev_event_hash"`
	EventHash       string             `json:"event_hash"`
	Payload         json.RawMessage    `json:"payload"`
}

type EventArtifact struct {
	ID         uuid.UUID    `json:"id"`
	EventID    uuid.UUID    `json:"event_id"`
	ArtifactID uuid.UUID    `json:"artifact_id"`
	Role       ArtifactRole `json:"role"`
}

type EventLineage struct {
	ID            uuid.UUID `json:"id"`
	ParentEventID uuid.UUID `json:"parent_event_id"`
	ChildEventID  uuid.UUID `json:"child_event_id"`
	Relationship  string    `json:"relationship"`
}

// Append-only. A new assessment is a new row, not an update.
type EventScore struct {
	ID        uuid.UUID      `json:"id"`
	EventID   uuid.UUID      `json:"event_id"`
	Type      ScoreType      `json:"type"`
	Value     pgtype.Numeric `json:"value"`
	Category  ScoreCategory  `json:"category"`
	ScoredBy  pgtype.UUID    `json:"scored_by"`
	Reason    *string        `json:"reason"`
	Metadata  []byte         `json:"metadata"`
	CreatedAt time.Time      `json:"created_at"`
}

// Mutable table — this is configuration, not event data. New versions of an event type get new rows; old rows are deactivated (is_active = false), never deleted.
type EventTypeRegistry struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	Version        string    `json:"version"`
	Description    *string   `json:"description"`
	PayloadSchema  []byte    `json:"payload_schema"`
	AllowedIntents []string  `json:"allowed_intents"`
	IsActive       bool      `json:"is_active"`
	CreatedAt      time.Time `json:"created_at"`
}

type Scope struct {
	ID          uuid.UUID `json:"id"`
	Project     string    `json:"project"`
	Domain      *string   `json:"domain"`
	Environment *string   `json:"environment"`
	CreatedAt   time.Time `json:"created_at"`
}
