// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Lineage Support",
            "url": "https://github.com/vkrishna03/Lineage"
        },
        "license": {
            "name": "Elastic License 2.0",
            "url": "https://www.elastic.co/licensing/elastic-license"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/actors": {
            "get": {
                "description": "List all actors",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actors"
                ],
                "summary": "List actors",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_actor.ListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new actor (human, llm, agent, service, or tool)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actors"
                ],
                "summary": "Create an actor",
                "parameters": [
                    {
                        "description": "Actor creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_actor.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_actor.ActorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/actors/{id}": {
            "get": {
                "description": "Get an actor by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actors"
                ],
                "summary": "Get an actor",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Actor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_actor.ActorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/artifacts": {
            "get": {
                "description": "List artifacts by scope, or find a specific artifact by scope and content hash (for deduplication)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "artifacts"
                ],
                "summary": "List or find artifacts",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Scope ID",
                        "name": "scope_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Content hash (if provided, returns single artifact)",
                        "name": "content_hash",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "When content_hash is provided",
                        "schema": {
                            "$ref": "#/definitions/internal_artifact.ArtifactResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new artifact with content hash for deduplication",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "artifacts"
                ],
                "summary": "Create an artifact",
                "parameters": [
                    {
                        "description": "Artifact creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_artifact.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_artifact.ArtifactResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/artifacts/{id}": {
            "get": {
                "description": "Get an artifact by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "artifacts"
                ],
                "summary": "Get an artifact",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Artifact ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_artifact.ArtifactResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/event-types": {
            "get": {
                "description": "List all active event types",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event-types"
                ],
                "summary": "List event types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_eventtype.ListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new event type with optional JSON schema for payload validation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event-types"
                ],
                "summary": "Create an event type",
                "parameters": [
                    {
                        "description": "Event type creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_eventtype.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_eventtype.EventTypeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/event-types/{id}": {
            "get": {
                "description": "Get an event type by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event-types"
                ],
                "summary": "Get an event type",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Event Type ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_eventtype.EventTypeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/events": {
            "get": {
                "description": "List all events in a scope, ordered by scope_sequence",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "List events by scope",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Scope ID",
                        "name": "scope_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_event.ListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Submit an event to the processing queue. Events are processed asynchronously and will be hash-chained.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Create an event",
                "parameters": [
                    {
                        "description": "Event creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_event.Input"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/internal_event.CreateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/events/{id}": {
            "get": {
                "description": "Get an event by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Get an event",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_event.EventResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/events/{id}/artifacts": {
            "get": {
                "description": "Get all artifacts linked to an event",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "artifacts"
                ],
                "summary": "Get artifacts for event",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_artifact.ListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Link an existing artifact to an event as input or output",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "artifacts"
                ],
                "summary": "Link artifact to event",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Link request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_artifact.LinkRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/events/{id}/lineage": {
            "get": {
                "description": "Get parent and child events for a given event",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Get event lineage",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_event.LineageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/events/{id}/scores": {
            "get": {
                "description": "Get all scores for an event, optionally filtered by type",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scores"
                ],
                "summary": "Get scores for event",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "confidence",
                            "relevance",
                            "reliability",
                            "agreement"
                        ],
                        "type": "string",
                        "description": "Filter by score type",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_score.ListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Add a new score (confidence, relevance, reliability, agreement) to an event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scores"
                ],
                "summary": "Add score to event",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Score creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_score.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_score.ScoreResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check the health of the API and its dependencies (Postgres, Kafka)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_health.Response"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/internal_health.Response"
                        }
                    }
                }
            }
        },
        "/scopes": {
            "get": {
                "description": "List all scopes",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scopes"
                ],
                "summary": "List scopes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_scope.ListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new scope for grouping events",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scopes"
                ],
                "summary": "Create a scope",
                "parameters": [
                    {
                        "description": "Scope creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_scope.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_scope.ScopeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/scopes/{id}": {
            "get": {
                "description": "Get a scope by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scopes"
                ],
                "summary": "Get a scope",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Scope ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_scope.ScopeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_actor.ActorResponse": {
            "description": "Actor data returned by the API",
            "type": "object",
            "properties": {
                "external_id": {
                    "type": "string",
                    "example": "claude-opus-4"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "metadata": {
                    "type": "object"
                },
                "name": {
                    "type": "string",
                    "example": "Claude"
                },
                "registered_at": {
                    "type": "string",
                    "example": "2024-01-15T10:00:00Z"
                },
                "type": {
                    "type": "string",
                    "example": "llm"
                }
            }
        },
        "internal_actor.CreateRequest": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "external_id": {
                    "type": "string",
                    "example": "claude-opus-4"
                },
                "metadata": {
                    "type": "object"
                },
                "name": {
                    "type": "string",
                    "example": "Claude"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "human",
                        "llm",
                        "agent",
                        "service",
                        "tool"
                    ],
                    "example": "llm"
                }
            }
        },
        "internal_actor.ListResponse": {
            "type": "object",
            "properties": {
                "actors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_actor.ActorResponse"
                    }
                },
                "count": {
                    "type": "integer"
                }
            }
        },
        "internal_artifact.ArtifactResponse": {
            "description": "Artifact data returned by the API",
            "type": "object",
            "properties": {
                "content_hash": {
                    "type": "string",
                    "example": "sha256:abc123..."
                },
                "content_type": {
                    "type": "string",
                    "example": "application/json"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-15T10:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "metadata": {
                    "type": "object"
                },
                "scope_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "uri": {
                    "type": "string",
                    "example": "s3://bucket/path/file.json"
                }
            }
        },
        "internal_artifact.CreateRequest": {
            "type": "object",
            "required": [
                "content_hash",
                "content_type",
                "scope_id"
            ],
            "properties": {
                "content_hash": {
                    "type": "string",
                    "example": "sha256:abc123..."
                },
                "content_type": {
                    "type": "string",
                    "example": "application/json"
                },
                "metadata": {
                    "type": "object"
                },
                "scope_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "uri": {
                    "type": "string",
                    "example": "s3://bucket/path/file.json"
                }
            }
        },
        "internal_artifact.LinkRequest": {
            "type": "object",
            "required": [
                "artifact_id",
                "role"
            ],
            "properties": {
                "artifact_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "input",
                        "output"
                    ],
                    "example": "input"
                }
            }
        },
        "internal_artifact.ListResponse": {
            "type": "object",
            "properties": {
                "artifacts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_artifact.ArtifactResponse"
                    }
                },
                "count": {
                    "type": "integer"
                }
            }
        },
        "internal_event.CreateResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Event queued for processing"
                },
                "status": {
                    "type": "string",
                    "example": "accepted"
                }
            }
        },
        "internal_event.EventResponse": {
            "description": "Event data returned by the API",
            "type": "object",
            "properties": {
                "actor_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440002"
                },
                "correction_type": {
                    "type": "string",
                    "example": "supersede"
                },
                "corrects_event_id": {
                    "type": "string"
                },
                "decided_at": {
                    "type": "string",
                    "example": "2024-01-15T10:35:00Z"
                },
                "event_hash": {
                    "type": "string",
                    "example": "def456..."
                },
                "event_type_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440003"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "ingested_at": {
                    "type": "string",
                    "example": "2024-01-15T10:40:00Z"
                },
                "intent": {
                    "type": "string",
                    "example": "decision"
                },
                "observed_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "payload": {},
                "prev_event_hash": {
                    "type": "string",
                    "example": "abc123..."
                },
                "reason": {
                    "type": "string",
                    "example": "User approved the recommendation"
                },
                "scope_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "scope_sequence": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_event.Input": {
            "type": "object",
            "properties": {
                "actor_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "confidence": {
                    "description": "Inline confidence score (optional, 0.0-1.0)",
                    "type": "number",
                    "example": 0.85
                },
                "correction_type": {
                    "type": "string",
                    "enum": [
                        "supersede",
                        "amend",
                        "retract"
                    ],
                    "example": "supersede"
                },
                "corrects_event_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440003"
                },
                "decided_at": {
                    "type": "string",
                    "example": "2024-01-15T10:35:00Z"
                },
                "event_type_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440002"
                },
                "input_artifact_ids": {
                    "description": "Inline artifact linking (optional)",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "intent": {
                    "type": "string",
                    "enum": [
                        "exploration",
                        "suggestion",
                        "assertion",
                        "decision",
                        "execution"
                    ],
                    "example": "decision"
                },
                "observed_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "output_artifact_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "parent_event_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "payload": {
                    "type": "object"
                },
                "reason": {
                    "type": "string",
                    "example": "User approved the recommendation"
                },
                "scope_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "internal_event.LineageResponse": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_event.EventResponse"
                    }
                },
                "event_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "parents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_event.EventResponse"
                    }
                }
            }
        },
        "internal_event.ListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_event.EventResponse"
                    }
                }
            }
        },
        "internal_eventtype.CreateRequest": {
            "type": "object",
            "required": [
                "name",
                "version"
            ],
            "properties": {
                "allowed_intents": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "exploration",
                        "suggestion",
                        "assertion",
                        "decision",
                        "execution"
                    ]
                },
                "description": {
                    "type": "string",
                    "example": "A decision event type"
                },
                "name": {
                    "type": "string",
                    "example": "decision"
                },
                "payload_schema": {
                    "type": "object"
                },
                "version": {
                    "type": "string",
                    "example": "1.0"
                }
            }
        },
        "internal_eventtype.EventTypeResponse": {
            "description": "Event type data returned by the API",
            "type": "object",
            "properties": {
                "allowed_intents": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "exploration",
                        "suggestion",
                        "assertion",
                        "decision",
                        "execution"
                    ]
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-15T10:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "A decision event type"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "decision"
                },
                "payload_schema": {
                    "type": "object"
                },
                "version": {
                    "type": "string",
                    "example": "1.0"
                }
            }
        },
        "internal_eventtype.ListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "event_types": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_eventtype.EventTypeResponse"
                    }
                }
            }
        },
        "internal_health.Response": {
            "type": "object",
            "properties": {
                "services": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "internal_scope.CreateRequest": {
            "type": "object",
            "required": [
                "project"
            ],
            "properties": {
                "domain": {
                    "type": "string",
                    "example": "payments"
                },
                "environment": {
                    "type": "string",
                    "example": "production"
                },
                "project": {
                    "type": "string",
                    "example": "my-project"
                }
            }
        },
        "internal_scope.ListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "scopes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_scope.ScopeResponse"
                    }
                }
            }
        },
        "internal_scope.ScopeResponse": {
            "description": "Scope data returned by the API",
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-01-15T10:00:00Z"
                },
                "domain": {
                    "type": "string",
                    "example": "payments"
                },
                "environment": {
                    "type": "string",
                    "example": "production"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "project": {
                    "type": "string",
                    "example": "my-project"
                }
            }
        },
        "internal_score.CreateRequest": {
            "type": "object",
            "required": [
                "type",
                "value"
            ],
            "properties": {
                "metadata": {
                    "type": "object"
                },
                "reason": {
                    "type": "string",
                    "example": "High confidence based on training data coverage"
                },
                "scored_by": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "confidence",
                        "relevance",
                        "reliability",
                        "agreement"
                    ],
                    "example": "confidence"
                },
                "value": {
                    "type": "number",
                    "example": 0.85
                }
            }
        },
        "internal_score.ListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "scores": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_score.ScoreResponse"
                    }
                }
            }
        },
        "internal_score.ScoreResponse": {
            "description": "Score data returned by the API",
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "example": "high"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-15T10:00:00Z"
                },
                "event_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "metadata": {
                    "type": "object"
                },
                "reason": {
                    "type": "string",
                    "example": "High confidence based on training data coverage"
                },
                "scored_by": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440002"
                },
                "type": {
                    "type": "string",
                    "example": "confidence"
                },
                "value": {
                    "type": "number",
                    "example": 0.85
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Lineage API",
	Description:      "Epistemic Transparency & Event Lineage System API\nAn append-only event store with hash-chaining for AI decision tracking",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
