// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_types.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createEventType = `-- name: CreateEventType :one
INSERT INTO event_type_registry (name, version, description, payload_schema, allowed_intents)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, version, description, payload_schema, allowed_intents, is_active, created_at
`

type CreateEventTypeParams struct {
	Name           string   `json:"name"`
	Version        string   `json:"version"`
	Description    *string  `json:"description"`
	PayloadSchema  []byte   `json:"payload_schema"`
	AllowedIntents []string `json:"allowed_intents"`
}

func (q *Queries) CreateEventType(ctx context.Context, arg CreateEventTypeParams) (EventTypeRegistry, error) {
	row := q.db.QueryRow(ctx, createEventType,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.PayloadSchema,
		arg.AllowedIntents,
	)
	var i EventTypeRegistry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.PayloadSchema,
		&i.AllowedIntents,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateEventType = `-- name: DeactivateEventType :exec
UPDATE event_type_registry SET is_active = false WHERE id = $1
`

func (q *Queries) DeactivateEventType(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateEventType, id)
	return err
}

const getEventType = `-- name: GetEventType :one
SELECT id, name, version, description, payload_schema, allowed_intents, is_active, created_at FROM event_type_registry WHERE id = $1
`

func (q *Queries) GetEventType(ctx context.Context, id uuid.UUID) (EventTypeRegistry, error) {
	row := q.db.QueryRow(ctx, getEventType, id)
	var i EventTypeRegistry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.PayloadSchema,
		&i.AllowedIntents,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getEventTypeByNameVersion = `-- name: GetEventTypeByNameVersion :one
SELECT id, name, version, description, payload_schema, allowed_intents, is_active, created_at FROM event_type_registry WHERE name = $1 AND version = $2
`

type GetEventTypeByNameVersionParams struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

func (q *Queries) GetEventTypeByNameVersion(ctx context.Context, arg GetEventTypeByNameVersionParams) (EventTypeRegistry, error) {
	row := q.db.QueryRow(ctx, getEventTypeByNameVersion, arg.Name, arg.Version)
	var i EventTypeRegistry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.PayloadSchema,
		&i.AllowedIntents,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveEventTypes = `-- name: ListActiveEventTypes :many
SELECT id, name, version, description, payload_schema, allowed_intents, is_active, created_at FROM event_type_registry WHERE is_active = true ORDER BY name, version
`

func (q *Queries) ListActiveEventTypes(ctx context.Context) ([]EventTypeRegistry, error) {
	rows, err := q.db.Query(ctx, listActiveEventTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventTypeRegistry{}
	for rows.Next() {
		var i EventTypeRegistry
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Description,
			&i.PayloadSchema,
			&i.AllowedIntents,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
