// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_artifacts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getArtifactsForEvent = `-- name: GetArtifactsForEvent :many
SELECT a.id, a.scope_id, a.content_hash, a.content_type, a.uri, a.metadata, a.created_at FROM artifacts a
JOIN event_artifacts ea ON ea.artifact_id = a.id
WHERE ea.event_id = $1
`

func (q *Queries) GetArtifactsForEvent(ctx context.Context, eventID uuid.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, getArtifactsForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.ContentHash,
			&i.ContentType,
			&i.Uri,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsForArtifact = `-- name: GetEventsForArtifact :many
SELECT e.id, e.scope_id, e.actor_id, e.event_type_id, e.scope_sequence, e.intent, e.reason, e.correction_type, e.corrects_event_id, e.observed_at, e.decided_at, e.ingested_at, e.prev_event_hash, e.event_hash, e.payload FROM events e
JOIN event_artifacts ea ON ea.event_id = e.id
WHERE ea.artifact_id = $1
`

func (q *Queries) GetEventsForArtifact(ctx context.Context, artifactID uuid.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsForArtifact, artifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.ActorID,
			&i.EventTypeID,
			&i.ScopeSequence,
			&i.Intent,
			&i.Reason,
			&i.CorrectionType,
			&i.CorrectsEventID,
			&i.ObservedAt,
			&i.DecidedAt,
			&i.IngestedAt,
			&i.PrevEventHash,
			&i.EventHash,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInputArtifactsForEvent = `-- name: GetInputArtifactsForEvent :many
SELECT a.id, a.scope_id, a.content_hash, a.content_type, a.uri, a.metadata, a.created_at FROM artifacts a
JOIN event_artifacts ea ON ea.artifact_id = a.id
WHERE ea.event_id = $1 AND ea.role = 'input'
`

func (q *Queries) GetInputArtifactsForEvent(ctx context.Context, eventID uuid.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, getInputArtifactsForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.ContentHash,
			&i.ContentType,
			&i.Uri,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutputArtifactsForEvent = `-- name: GetOutputArtifactsForEvent :many
SELECT a.id, a.scope_id, a.content_hash, a.content_type, a.uri, a.metadata, a.created_at FROM artifacts a
JOIN event_artifacts ea ON ea.artifact_id = a.id
WHERE ea.event_id = $1 AND ea.role = 'output'
`

func (q *Queries) GetOutputArtifactsForEvent(ctx context.Context, eventID uuid.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, getOutputArtifactsForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.ContentHash,
			&i.ContentType,
			&i.Uri,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkArtifact = `-- name: LinkArtifact :one
INSERT INTO event_artifacts (event_id, artifact_id, role)
VALUES ($1, $2, $3)
RETURNING id, event_id, artifact_id, role
`

type LinkArtifactParams struct {
	EventID    uuid.UUID    `json:"event_id"`
	ArtifactID uuid.UUID    `json:"artifact_id"`
	Role       ArtifactRole `json:"role"`
}

func (q *Queries) LinkArtifact(ctx context.Context, arg LinkArtifactParams) (EventArtifact, error) {
	row := q.db.QueryRow(ctx, linkArtifact, arg.EventID, arg.ArtifactID, arg.Role)
	var i EventArtifact
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ArtifactID,
		&i.Role,
	)
	return i, err
}
