// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scopes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createScope = `-- name: CreateScope :one
INSERT INTO scopes (project, domain, environment)
VALUES ($1, $2, $3)
RETURNING id, project, domain, environment, created_at
`

type CreateScopeParams struct {
	Project     string  `json:"project"`
	Domain      *string `json:"domain"`
	Environment *string `json:"environment"`
}

func (q *Queries) CreateScope(ctx context.Context, arg CreateScopeParams) (Scope, error) {
	row := q.db.QueryRow(ctx, createScope, arg.Project, arg.Domain, arg.Environment)
	var i Scope
	err := row.Scan(
		&i.ID,
		&i.Project,
		&i.Domain,
		&i.Environment,
		&i.CreatedAt,
	)
	return i, err
}

const getScope = `-- name: GetScope :one
SELECT id, project, domain, environment, created_at FROM scopes WHERE id = $1
`

func (q *Queries) GetScope(ctx context.Context, id uuid.UUID) (Scope, error) {
	row := q.db.QueryRow(ctx, getScope, id)
	var i Scope
	err := row.Scan(
		&i.ID,
		&i.Project,
		&i.Domain,
		&i.Environment,
		&i.CreatedAt,
	)
	return i, err
}

const getScopeByProject = `-- name: GetScopeByProject :one
SELECT id, project, domain, environment, created_at FROM scopes
WHERE project = $1
  AND (domain = $2 OR (domain IS NULL AND $2 IS NULL))
  AND (environment = $3 OR (environment IS NULL AND $3 IS NULL))
`

type GetScopeByProjectParams struct {
	Project     string  `json:"project"`
	Domain      *string `json:"domain"`
	Environment *string `json:"environment"`
}

func (q *Queries) GetScopeByProject(ctx context.Context, arg GetScopeByProjectParams) (Scope, error) {
	row := q.db.QueryRow(ctx, getScopeByProject, arg.Project, arg.Domain, arg.Environment)
	var i Scope
	err := row.Scan(
		&i.ID,
		&i.Project,
		&i.Domain,
		&i.Environment,
		&i.CreatedAt,
	)
	return i, err
}

const listScopes = `-- name: ListScopes :many
SELECT id, project, domain, environment, created_at FROM scopes ORDER BY created_at DESC
`

func (q *Queries) ListScopes(ctx context.Context) ([]Scope, error) {
	rows, err := q.db.Query(ctx, listScopes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scope{}
	for rows.Next() {
		var i Scope
		if err := rows.Scan(
			&i.ID,
			&i.Project,
			&i.Domain,
			&i.Environment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
